### ISSUE TITLE
Carousel resizing doesn't work correctly on IE10

### ISSUE THREAD

**Issue by sarukuku** [leandrowd/react-responsive-carousel#133]
See the attached video & images. I ran into this when I was doing browser testing for our company project where we use react-responsive-carousel. Any idea how this could be fixed? I've been playing around with styles for a while but haven't been able to figure out a fix. I'd also prefer getting the fix into "core" instead of overriding styles just for our project. :)

**Screenshot of the bug on IE 10**  
![screen shot 2017-05-31 at 11 26 54](https://cloud.githubusercontent.com/assets/1204559/26622800/34b845f0-45f4-11e7-8f3d-0f5c3acd18a4.png)

**Video of the bug on IE 10**  
[IE10.mp4.zip](https://github.com/leandrowd/react-responsive-carousel/files/1040715/IE10.mp4.zip)

**Comment by sarukuku** [comment]
In our project the problem can be fixed by overriding these styles.

```css
/* Fix for IE10 */
.carousel .slide {
  width: 100%;
}

/* Fix for IE10 */
.carousel .slide img {
  width: 100% !important;
  height: auto !important;
}
```
